In [243]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
base="ivory"

In [244]:
#df=pd.read_csv(f"./{base}/{base}_feature_engineered.csv")
df = pd.read_csv(f'{base}/{base}_usercount_classifier0.csv')

In [245]:
df.head()

,Unnamed: 0,handle,username,tweets,num_flagged_tweets,followers_count,post_freq,std_dev,avg_tweet_length,num_scraped_tweets
0,0,@010102iv000,0000000OOOOOOO,[{'tweet_link': '/010102iv000/status/142040069...,0,"1,312",3.655609,1.115725e+18,79.597938,138
1,1,@01Dongdongiii15,Ïï†Ïù¥ÎûòÎ•¥,[{'tweet_link': '/01Dongdongiii15/status/16197...,0,135,84.453892,1.411231e+18,82.181818,12
2,2,@022_mariska,Lech+Czech+Rus,[{'tweet_link': '/022_mariska/status/179051895...,1,440,2.006991,2.081324e+18,77.550562,2
3,3,@0320to0208,hyunin,[{'tweet_link': '/0320to0208/status/1731691189...,0,"9,294",3.936000,1.818889e+18,30.032258,50
4,4,@0K_ultra,OŒ∫ULTRA XPüßø,[{'tweet_link': '/0K_ultra/status/178633431267...,1,"3,204",41.149945,1.444426e+18,127.380952,12

In [246]:
df.dtypes

Unnamed: 0              int64
handle                 object
username               object
tweets                 object
num_flagged_tweets      int64
followers_count        object
post_freq             float64
std_dev               float64
avg_tweet_length      float64
num_scraped_tweets      int64
dtype: object

In [247]:
df['proportion_flagged'] = df['num_flagged_tweets']/df['num_scraped_tweets']
columns = ['handle', 'followers_count','post_freq','std_dev','avg_tweet_length', 'proportion_flagged']
df = df[columns]

In [248]:
df.head()

,handle,followers_count,post_freq,std_dev,avg_tweet_length,proportion_flagged
0,@010102iv000,"1,312",3.655609,1.115725e+18,79.597938,0.000000
1,@01Dongdongiii15,135,84.453892,1.411231e+18,82.181818,0.000000
2,@022_mariska,440,2.006991,2.081324e+18,77.550562,0.500000
3,@0320to0208,"9,294",3.936000,1.818889e+18,30.032258,0.000000
4,@0K_ultra,"3,204",41.149945,1.444426e+18,127.380952,0.083333

In [249]:
df.dtypes

handle                 object
followers_count        object
post_freq             float64
std_dev               float64
avg_tweet_length      float64
proportion_flagged    float64
dtype: object

In [250]:
columns = ['followers_count','post_freq','std_dev','avg_tweet_length']
column = columns[0]
def floatify(row):
    temp = str(row[column]).replace(',','')
    return float(temp)
df[column]=df.apply(floatify,axis=1)

df.head()

,handle,followers_count,post_freq,std_dev,avg_tweet_length,proportion_flagged
0,@010102iv000,1312.0,3.655609,1.115725e+18,79.597938,0.000000
1,@01Dongdongiii15,135.0,84.453892,1.411231e+18,82.181818,0.000000
2,@022_mariska,440.0,2.006991,2.081324e+18,77.550562,0.500000
3,@0320to0208,9294.0,3.936000,1.818889e+18,30.032258,0.000000
4,@0K_ultra,3204.0,41.149945,1.444426e+18,127.380952,0.083333

In [251]:
## we can plot each distribution to fit it to the actual values
import pandas as pd
from sklearn.preprocessing import RobustScaler, StandardScaler, QuantileTransformer
columns = ['followers_count','post_freq','std_dev','avg_tweet_length','proportion_flagged']
for column in columns:
    qt = QuantileTransformer(output_distribution='normal')
    df[[column]]=qt.fit_transform(df[[column]])
    # scaler = StandardScaler()
    # df[column]=scaler.fit_transform(df[[column]])  # Fit only on the column you want to normalize

In [252]:
for column in columns:
    print(column)
    print(df[column].min(),df[column].max())

followers_count
-5.199337582605575 5.19933758270342
post_freq
-5.199337582605575 5.19933758270342
std_dev
-5.199337582605575 5.19933758270342
avg_tweet_length
-5.199337582605575 5.19933758270342
proportion_flagged
-5.199337582605575 5.19933758270342

In [253]:
df.head()

,handle,followers_count,post_freq,std_dev,avg_tweet_length,proportion_flagged
0,@010102iv000,0.119149,-0.226778,-0.599765,-0.369839,-5.199338
1,@01Dongdongiii15,-0.840906,1.737546,-0.218714,-0.321049,-5.199338
2,@022_mariska,-0.331756,-0.538267,1.505747,-0.406070,2.256745
3,@0320to0208,0.840109,-0.183555,0.371087,-1.709977,-5.199338
4,@0K_ultra,0.475214,1.192245,-0.179846,0.384524,1.517545

In [254]:
##Convert to absolute values for the desired ones
#followers_count: low
df['followers_count'] = -df['followers_count']

In [255]:
#post_freq: extremes
columns = ['post_freq','std_dev','avg_tweet_length']
for column in columns:
    df[column] = abs(df[column])

In [256]:
columns = ['followers_count','post_freq','std_dev','avg_tweet_length','proportion_flagged']
for column in columns:
    qt = QuantileTransformer(output_distribution='normal')
    df[[column]]=qt.fit_transform(df[[column]])
    # scaler = StandardScaler()
    # df[column]=scaler.fit_transform(df[[column]])  # Fit only on the column you want to normalize

In [257]:
df.head()

,handle,followers_count,post_freq,std_dev,avg_tweet_length,proportion_flagged
0,@010102iv000,-0.119175,-0.918002,-0.122756,-0.556891,-5.199338
1,@01Dongdongiii15,0.840906,1.384969,-0.941932,-0.669298,-5.199338
2,@022_mariska,0.331756,-0.228925,1.116369,-0.480952,2.256745
3,@0320to0208,-0.840104,-1.055450,-0.555492,1.358661,-5.199338
4,@0K_ultra,-0.475214,0.729296,-1.068379,-0.526472,1.517545

In [258]:
from sklearn.decomposition import PCA

In [259]:
pca = PCA(n_components=1)
columns = ['followers_count','post_freq','std_dev','avg_tweet_length', 'proportion_flagged']

df['pca_score'] = pca.fit_transform(df[columns])
df['pca_rank'] = df['pca_score'].rank(ascending=False)

In [260]:
df.head()

,handle,followers_count,post_freq,std_dev,avg_tweet_length,proportion_flagged,pca_score,pca_rank
0,@010102iv000,-0.119175,-0.918002,-0.122756,-0.556891,-5.199338,-1.828746,2778.0
1,@01Dongdongiii15,0.840906,1.384969,-0.941932,-0.669298,-5.199338,-1.879098,4391.0
2,@022_mariska,0.331756,-0.228925,1.116369,-0.480952,2.256745,5.577771,77.0
3,@0320to0208,-0.840104,-1.055450,-0.555492,1.358661,-5.199338,-1.879803,4417.0
4,@0K_ultra,-0.475214,0.729296,-1.068379,-0.526472,1.517545,4.844432,438.0

In [261]:
sorted_df = df.sort_values(by='pca_rank', ascending=True)

In [262]:
sorted_df

,handle,followers_count,post_freq,std_dev,avg_tweet_length,proportion_flagged,pca_score,pca_rank
4474,@chubchubb90,0.715218,-1.584449,1.414698,-1.172631,5.199338,8.575985,1.0
5376,@kreyol_pale,0.751333,0.203862,1.044409,-1.741798,3.137285,6.486171,2.0
3025,@RogueAgentChaos,0.559858,-0.566589,1.225943,-0.865843,3.137285,6.478470,3.0
234,@AndikG_62,0.085834,-0.239467,-0.011672,-1.790504,3.089935,6.468730,4.0
6668,@wonky_tusk,0.993800,-1.029075,1.255470,-1.539850,3.089935,6.466908,5.0
...,...,...,...,...,...,...,...,...
286,@ArmandKleinX,-1.370479,5.199338,0.071899,0.116989,-5.199338,-2.040259,6774.0
4698,@eenopslaghier,-0.107218,2.904514,-0.134323,2.849874,-5.199338,-2.050585,6775.0
790,@CreepyTopic,-0.137510,3.102797,0.589449,2.775734,-5.199338,-2.065739,6776.0
786,@CreandomemesRDc,-0.395815,0.808256,1.255470,5.199338,-5.199338,-2.084040,6777.0
5245,@jorgealbert15,-0.368557,0.935576,1.255470,5.199338,-5.199338,-2.087801,6778.0

In [263]:
sorted_df.to_csv(f'{base}/{base}_ranking_classifier0_ranking0.csv')